# Generated by Django 4.1 on 2022-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.BigIntegerField()),
                ('Book_Title', models.CharField(max_length=255, null=True)),
                ('Book_Author', models.CharField(max_length=255, null=True)),
                ('Year_Of_Publication', models.DateField(auto_now=True)),
                ('Publisher', models.CharField(max_length=255, null=True)),
                ('Image_URL_S', models.CharField(max_length=255, null=True)),
                ('Image_URL_M', models.CharField(max_length=255, null=True)),
                ('Image_URL_L', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
