# Generated by Django 4.1 on 2022-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_alter_csvmodel_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='ISBN',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
