# Generated by Django 4.1 on 2022-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0005_fileuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
