# Generated by Django 4.1 on 2022-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0006_alter_fileuploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='ISBN',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
